#
# User configuration sourced by interactive shells
#


export LC_ALL=en_US.UTF-8  
export LANG=en_US.UTF-8

# Define zim location
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Start zim
[[ -s ${ZIM_HOME}/init.zsh ]] && source ${ZIM_HOME}/init.zsh

export PATH="$PATH:/Users/oleg/.dotnet/tools"

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/oleg/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/oleg/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/oleg/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/oleg/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

